### ISSUE TITLE
About your BigDebuffs.

### ISSUE THREAD

**Issue by dabadoo** [nozzlegear/bigdebuffs#1]
Hello!

Sorry for creating an issue here when it's about your bigdebuffs fork. When clicking the link https://github.com/nozzlegear/bigdebuffs/issues I get auto directed to https://github.com/nozzlegear/bigdebuffs/pulls instead. So I was not sure how to create an issue.

I've tried installing your djuxdebuffs 1.0.3 but it doesn't work in game and I get 4 errors when logging in.

1:
>2x DjuxDebuffs/Options.lua:1: Usage: GetAddon(name): 'name' - Cannot find an AceAddon 'BigDebuffs'.
[string "=[C]"]: ?
[string "@AdvancedRaidFrameSettings/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:151: in function `GetAddon'
[string "@DjuxDebuffs/Options.lua"]:1: in main chunk
Locals:
(*temporary) = "Usage: GetAddon(name): 'name' - Cannot find an AceAddon 'BigDebuffs'."

2:
>2x DjuxDebuffs/BigDebuffs.lua:781: attempt to call method 'SetupOptions' (a nil value)
[string "@DjuxDebuffs/BigDebuffs.lua"]:781: in function <DjuxDebuffs/BigDebuffs.lua:725>
[string "=[C]"]: ?
[string "@AdvancedRaidFrameSettings/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...RaidFrameSettings/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@AdvancedRaidFrameSettings/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@AdvancedRaidFrameSettings/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <...RaidFrameSettings/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

3:
>2x DjuxDebuffs/Options.lua:1 (null)

4:
>2x Interface\FrameXML\Bindings.xml:1 DjuxDebuffs/Options.lua:1 (null)

**Comment by nozzlegear** [comment]
Thanks for the heads up! I didn't realize issues were disabled on this repository. I've enabled them now and transferred this over.

**Comment by nozzlegear** [comment]
I ran into this error myself earlier today. I'm not super familiar with the code yet but I think it's trying to load the options for BigDebuffs and failing to do that since I had to rename the addon DjuxDebuffs to publish it. Should be a simple fix (famous last words). I'll take a crack at it soon.

**Comment by nozzlegear** [comment]
@dabadoo Okay, I think this is fixed with 1.0.4! Give it a try and let me know how it works.

**Comment by dabadoo** [comment]
No errors on login and options menu work. Looking forward to try it out =)
