### ISSUE TITLE
Mindgames not showing up.

### ISSUE THREAD

**Issue by dabadoo** [nozzlegear/bigdebuffs#2]
I have enabled it under spells and checked in under warning debuffs. Doesn't show up.
I tried replacing it myself with this id for mindgames: 375901.
It showed up but it was small and changing sizes under settings didn't seem to do much. It didn't have the same size as the other warning debuffs.

**Comment by nozzlegear** [comment]
Should be fixed in 1.0.5!

**Comment by dabadoo** [comment]
The fix has the same issues as when I tried adding it myself. Mindgames stays small even when ticked as a warning debuff and changing the size for only mindgames doesn't do anything.

https://imgur.com/a/EHRQGmb

Is this an issue on my end? Not getting any errors.

**Comment by dabadoo** [comment]
Some more testing. Tried disabling all addons except Your addon and deleted its saved variables.
Set offensive debuffs to 100%. Mindgames stays small. Stuff like vampiric and devouring plague was huge.
In a random duel with a lock I discovered that other offensive debuffs such as soul rot also stayed small while it was supposed to be at 100% size.

**Comment by nozzlegear** [comment]
Hmm interesting, thanks for testing it. I've noticed the same problem myself, I can't get mindgames or soulrot to show up as part of the big debuffs even after merging the fixes from upstream. I'm going to be doing some arenas tonight, I'll test some fixes and see if I can narrow this down.

--
Josh Harms

**Comment by nozzlegear** [comment]
Okay I've done some testing, using the latest version 1.0.5, Mindgames does show up for me but it doesn't seem to respect the size settings.

**Comment by nozzlegear** [comment]
@dabadoo I think this is fixed in 1.0.8, give it a try!

**Comment by dabadoo** [comment]
From a quick test in a duel:
Mindgames did change in size when I gave it a custom size. But the size didn't seem to get bigger after 50-60%.
Mindgames when checked as a warning debuff did not follow the size set by warning debuffs. Only custom size worked for it.
Vampiric touch, which worked fine previously when checked as a warning debuff, did no longer work. It now followed the sizing rules of offensive debuffs.

**Comment by nozzlegear** [comment]
Thanks. I'm not sure if you mentioned, are you using default Blizzard raid frames?

**Comment by dabadoo** [comment]
Yes. I use default raidframes with other addons adding on to it like:
Enhanced Raid Frames (only using it to display water shield in top right corner)
RaidFrameSettings (previously known as Advanced Raid Frame Settings)
Party Raidframe Resize
PartyPets Fix

**Comment by nozzlegear** [comment]
Just an update, I've been asked to remove this addon from wago and contribute changes back to the original BigDebuffs instead. I'm going to be doing that, so it'd be best to file this issue over there if you're still running into it. Thanks for the help, and thinks for giving the addon a try!

**Comment by dabadoo** [comment]
Understandable. Big thanks for trying to revive the addon while the original author was away.
