### ISSUE TITLE
Error in raids

### ISSUE THREAD

**Issue by dabadoo** [nozzlegear/bigdebuffs#4]
Getting a variation of this error in raid groups. Sometimes the number of "'CompactRaidFrame1:SetAttribute()'" is different.

1x [ADDON_ACTION_BLOCKED] AddOn 'DjuxDebuffs' tried to call the protected function 'CompactRaidFrame1:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/CompactUnitFrame.lua"]:174: in function `CompactUnitFrame_SetUnit'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua"]:27: in function `releaseFunc'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameReservationManager.lua"]:27: in function `CompactRaidFrameReservation_ReleaseUnusedReservations'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua"]:346: in function `ReleaseAllReservedFrames'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua"]:178: in function `LayoutFrames'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua"]:128: in function `TryUpdate'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua"]:52: in function <...actRaidFrames/Blizzard_CompactRaidFrameContainer.lua:50>

**Comment by dabadoo** [comment]
Also happned in a dungeon. So probably just when using raid frames in general.

**Comment by dabadoo** [comment]
This error happned after every boss kill in a dungeon and bugged the frames.

1x [ADDON_ACTION_BLOCKED] AddOn 'DjuxDebuffs' tried to call the protected function 'CompactPartyFrameMember4:Show()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `Show'
[string "@FrameXML/CompactUnitFrame.lua"]:394: in function `CompactUnitFrame_UpdateVisible'
[string "@FrameXML/CompactUnitFrame.lua"]:319: in function <FrameXML/CompactUnitFrame.lua:317>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `CompactUnitFrame_UpdateAll'
[string "@FrameXML/CompactUnitFrame.lua"]:145: in function <FrameXML/CompactUnitFrame.lua:47>

edit: also seems to happen in BGs and arenas. Sometimes it breaks the frames. Sometimes not.

**Comment by nozzlegear** [comment]
Thanks! I haven't used this addon in a raid or dungeon yet so haven't seen this myself. I see this is also an issue in the original addon and there's an open pull request that looks like it might fix it. I'll test it out and see if that fixes things.

**Comment by dabadoo** [comment]
Not sure if useful... But when someone levels up while doing dungeons it also seems to bug the frames. Error message seems to be the same.

**Comment by nozzlegear** [comment]
That's useful, thanks! Very strange thing to bug the frames but it gives me a little clue as to what to look for.

**Comment by nozzlegear** [comment]
I think this issue is fixed in 1.0.7. Give it a try and let me know!

**Comment by dabadoo** [comment]
Did a quick dungeon run and got this error after every boss kill.

15x [ADDON_ACTION_BLOCKED] AddOn 'DjuxDebuffs' tried to call the protected function 'CompactPartyFrameMember4:Show()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `Show'
[string "@FrameXML/CompactUnitFrame.lua"]:394: in function `CompactUnitFrame_UpdateVisible'
[string "@FrameXML/CompactUnitFrame.lua"]:319: in function <FrameXML/CompactUnitFrame.lua:317>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `CompactUnitFrame_UpdateAll'
[string "@FrameXML/CompactUnitFrame.lua"]:145: in function <FrameXML/CompactUnitFrame.lua:47>

**Comment by nozzlegear** [comment]
Thanks! Looks like that didn’t do it, I’ve got another idea for a fix, I’ll get it published soon.

--
Josh Harms

**Comment by nozzlegear** [comment]
I've published version 1.0.8 with a big change for raid/party frames. I don't think it has fixed everything for this error but it should stop things like the raid frames disappearing when group size changes. Can you give it a try and let me know how it works?

**Comment by dabadoo** [comment]
Got a couple of different error messages throughout a quick dungeon run. Frames still seemed to bug out visually after boss kills.
After the first boss in ruby life pools the frames didn't bug out visually BUT some of the frames couldn't be clicked afterwards.
Clique, which I use for mouseover healing in dungeons, did not work at all throughout the dungeon. I had to manually click the frames.

Errors in random order:
--1:

3x [ADDON_ACTION_BLOCKED] AddOn 'DjuxDebuffs' tried to call the protected function 'CompactPartyFrameMember3:Show()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `Show'
[string "@FrameXML/CompactUnitFrame.lua"]:394: in function <FrameXML/CompactUnitFrame.lua:387>
[string "=[C]"]: in function `CompactUnitFrame_UpdateVisible'
[string "@FrameXML/CompactUnitFrame.lua"]:319: in function <FrameXML/CompactUnitFrame.lua:317>
[string "=[C]"]: ?
[string "=[C]"]: in function `CompactUnitFrame_UpdateAll'
[string "@FrameXML/CompactUnitFrame.lua"]:116: in function <FrameXML/CompactUnitFrame.lua:47>


--2:

15x ...uffs/BlizzardRaidFramesFix/BlizzardRaidFramesFix.lua:573: assertion failed!
[string "=[C]"]: in function `assert'
[string "@DjuxDebuffs/BlizzardRaidFramesFix/BlizzardRaidFramesFix.lua"]:573: in function <...uffs/BlizzardRaidFramesFix/BlizzardRaidFramesFix.lua:566>
[string "=[C]"]: in function `CompactUnitFrame_SetUnit'
[string "@FrameXML/CompactPartyFrame.lua"]:55: in function <FrameXML/CompactPartyFrame.lua:28>

Locals:
(*temporary) = false


--3:

1x [ADDON_ACTION_BLOCKED] AddOn 'DjuxDebuffs' tried to call the protected function 'CompactPartyFrameMember1:Show()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `Show'
[string "@FrameXML/CompactUnitFrame.lua"]:394: in function <FrameXML/CompactUnitFrame.lua:387>
[string "=[C]"]: in function `CompactUnitFrame_UpdateVisible'
[string "@FrameXML/CompactUnitFrame.lua"]:319: in function <FrameXML/CompactUnitFrame.lua:317>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `CompactUnitFrame_UpdateAll'
[string "@FrameXML/CompactUnitFrame.lua"]:220: in function <FrameXML/CompactUnitFrame.lua:218>
[string "=[C]"]: ?
[string "=[C]"]: in function `CompactUnitFrame_SetUpFrame'
[string "@FrameXML/CompactPartyFrame.lua"]:56: in function <FrameXML/CompactPartyFrame.lua:28>

**Comment by nozzlegear** [comment]
Oh I didn't expect that, it sounds like it made it worse then?

**Comment by dabadoo** [comment]
Yeah, I would unfortunately say so.

**Comment by nozzlegear** [comment]
As mentioned in the other issue, I've been asked to remove the addon from Wago and contribute changes back to BigDebuffs instead. I'll be doing that, please file this issue under BigDebuffs proper if you're still running into it!
